version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellyfin_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: "false"

  server:
    image: linuxserver/jellyfin:version-12.1ubu2604@sha256:83d3e38f1cc6b0d1f5663329825b1530613a403fc108cc07816733cf08fe796c
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      # Service auto-discovery
      - 7359:7359/udp
